package internal

import (
	"fmt"
	"go/types"
	"strings"

	"golang.org/x/tools/imports"
)

type TransformerType string

const (
	TransformerTypeFunction TransformerType = "function"
	TransformerTypeMethod   TransformerType = "method"
)

func TransformerTypeFromString(s string) (TransformerType, error) {
	switch s {
	case "function":
		return TransformerTypeFunction, nil
	case "method":
		return TransformerTypeMethod, nil
	default:
		return "", fmt.Errorf("invalid transformer type: %s", s)
	}
}

type GenerateOption struct {
	TransformerType TransformerType
	TramsformerName string
	DestinationPath string
}

func Generate(dst, src *Struct, opts *GenerateOption) (string, error) {
	tDst, err := dst.LookupType()
	if err != nil {
		return "", fmt.Errorf("failed to lookup dst type: %w", err)
	}
	tSrc, err := src.LookupType()
	if err != nil {
		return "", fmt.Errorf("failed to lookup src type: %w", err)
	}

	corr := GuessFieldCorrespondings(tDst, tSrc)

	var sb strings.Builder
	writeGeneratedComment(&sb)
	writePackageDecl(&sb, src)
	writeTransformer(&sb, dst, src, tSrc, opts, corr)

	formatted, err := imports.Process(opts.DestinationPath, []byte(sb.String()), nil)
	if err != nil {
		return "", fmt.Errorf("failed to process import: %w", err)
	}

	return string(formatted), nil
}

func writeGeneratedComment(sb *strings.Builder) {
	sb.WriteString("// This file is generated by github.com/utgwkk/go-transform-struct-gen\n")
}

func writePackageDecl(sb *strings.Builder, s *Struct) {
	sb.WriteString(fmt.Sprintf("package %s\n\n", s.PackageName))
}

func writeTransformer(sb *strings.Builder, dst, src *Struct, tSrc *types.Struct, opts *GenerateOption, corr map[string]string) {
	if opts.TransformerType == TransformerTypeFunction {
		sb.WriteString(fmt.Sprintf("func %s(src %s) %s {\n", opts.TramsformerName, src.ReturnTypeString(true), dst.ReturnTypeString(false)))
	} else {
		sb.WriteString(fmt.Sprintf("func (src %s) %s() %s {\n", src.ReturnTypeString(true), opts.TramsformerName, dst.ReturnTypeString(false)))
	}

	sb.WriteString(fmt.Sprintf(" return %s{\n", dst.LiteralTypeString()))

	for i := 0; i < tSrc.NumFields(); i++ {
		dstField := tSrc.Field(i)
		if !dstField.Exported() {
			continue
		}
		dstFieldName := dstField.Name()
		srcField, ok := corr[dstFieldName]
		if !ok {
			continue
		}
		sb.WriteString(fmt.Sprintf("  %s: src.%s,\n", dstFieldName, srcField))
	}

	sb.WriteString(" }\n")
	sb.WriteString("}\n")
}
